### PR TITLE
ceiling_date handles missing value propely

### LINKED ISSUE #486: ceiling_date doesn't work if NA present
As of version `1.6.0`, `ceiling_date` stopped working if the vector contains `NA` and unit `minute`, `hour`, or `day` (used to work in `1.5.6`)

```r 
library(lubridate)
dates <- c("02/27/92", "02/27/92", "01/14/92", "02/28/92", "02/01/92")
times <- c("23:03:20", "22:29:56", "01:03:30", "18:21:03", "16:56:26")
x <- paste(dates, times)
times <- strptime(x, "%m/%d/%y %H:%M:%S")
times[2] <- NA

floor_date(times, unit="day") # works fine 
ceiling_date(times, unit="day") # breaks
```

```
Error in `[<-.POSIXlt`(`*tmp*`, not_same, value = c(699231600, NA, 695430000,  : 
  NAs are not allowed in subscripted assignments
```

These are the offending lines in `round.R` (if `new` or `new1` contain `NA`): 

```r 
not_same <- new1 != new
new1[not_same] <- new1[not_same] + delta
```

### PR DESCRIPTION
**Pull request by cderv**
Proposition to fix #486 . 
I added some tests and News bullet point

---
This change is [Reviewable](https://reviewable.io/reviews/hadley/lubridate/488)

### CODE REVIEW

File: tests/testthat/test-round.R [hunk 1]
```diff
@@ -385,3 +385,14 @@ test_that("round_date and ceiling_date skip day time gap", {
 
   expect_equal(round_date(x, "hour"),  y)
 })
+
+test_that("ceiling_date behaves correctly with NA", {
+  ## (bug #486)
```
Comment (cderv) [inline tests/testthat/test-round.R]: Yes. I will do it as soon as possible.

**Comment by cderv** [comment]
I added some tests for round_date and floor_date using just some units not all possibilities.

**Comment by vspinu** [comment]
Thank you!
